config/routes.rb
Rails.application.routes.draw do
  
  root 'catalog#index'
  post '/' => 'catalog#index'

  namespace :admin do
    get '/' => 'admin#index'
    resources :products
    resources :categories
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :children, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent, :class_name => "Category"

  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :name, uniqueness: true

  scope :top_level, -> { where parent: nil }
  scope :sub_level, -> { top_level.map(&:children).flatten }
  scope :end_level, -> { sub_level.map(&:children).flatten }
  scope :parent_to_be, -> { top_level + sub_level }

  scope :with_product, -> do
    categories = Category.where id: ProductCategory.pluck(:category_id)
    categories_1 = categories.map(&:parent).compact
    categories_2 = categories_1.map(&:parent).compact
    (categories + categories_1 + categories_2).uniq
  end

  def all_product_ids
    if children.empty?
      product_ids
    else
      product_ids + children.map { |e| e.all_product_ids }
    end
  end

  def to_s
    name
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  validates :name, uniqueness: true

  def price
    "#{amount.to_f/100} SGD" rescue 'Free'
  end

  def to_s
    name
  end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category

  validates :product, uniqueness: { scope: :category,
    message: "should be in a category only once" }
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  def index
    redirect_to admin_products_path
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id, product_ids: [])
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :amount, category_ids: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @categories = Category.with_product
    if params[:categories]
      @selected_categories = Category.where id: params[:categories]
      @products = Product.where id: @selected_categories.map(&:all_product_ids)
    else
      @products = Product.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category], html: {class: "form-horizontal"}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :parent_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :parent_id, options_for_select(Category.parent_to_be.map{|cat| [cat, cat.id]}, @category.parent_id), {include_blank: true}, {class: 'form-control dropdown'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :products, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :product_ids, Product.all, :id, :name, {}, {multiple: true, class: 'form-control dropdown'} %>
    </div>
  </div>

  <div class="actions col-sm-offset-2">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_category_path(@category), class: 'btn btn-link' %>
<%= link_to 'Back', admin_categories_path, class: 'btn btn-link' %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Category</th>
      <th>Parent</th>
      <th>Children Count</th>
      <th>Products Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category %></td>
        <td><%= category.parent %></td>
        <td><%= category.children.count %></td>
        <td><%= category.products.count %></td>
        <td><%= link_to 'Show', admin_category_path(category), class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path, class: 'btn btn-primary' %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path, class: 'btn btn-link' %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category %>
</p>

<p>
  <% if @category.parent %>
    <strong>Parent:</strong>
    <%= link_to @category.parent, admin_category_path(@category.parent) %>
  <% else %>
    Top Level Category
  <% end %>
</p>

<% if @category.children.count > 0 %>
  <p>
    <strong>Sub Categories:</strong>
    <%= @category.children.map { |e| link_to e, admin_category_path(e)  }.join(', ').html_safe %>
  </p>
<% end %>

<p>
  <strong>Products:</strong>
  <% if @category.products.count > 0 %>
    <%= @category.products.map { |e| link_to e, admin_product_path(e) }.join(', ').html_safe %>
  <% else %>
    No Product
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category), class: 'btn btn-link' %>
<%= link_to 'Back', admin_categories_path, class: 'btn btn-link' %>

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], html: {class: "form-horizontal"}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, 'Price in cents', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.number_field :amount, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :categories, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :category_ids, Category.all, :id, :name, {}, {multiple: true, class: 'form-control dropdown'} %>
    </div>
  </div>

  <div class="actions col-sm-offset-2">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(@product), class: 'btn btn-link' %> |
<%= link_to 'Back', admin_products_path, class: 'btn btn-link' %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.categories.count %></td>
        <td><%= link_to 'Show', admin_product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path, class: 'btn btn-primary' %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path, class: 'btn btn-link' %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @product.categories.map { |e| link_to e, admin_category_path(e)  }.join(', ').html_safe %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-link' %>
<%= link_to 'Back', admin_products_path, class: 'btn btn-link' %>

app/views/catalog/index.html.erb
<h1>
  Product Catalog
</h1>
<div class="row well">
  <%= form_tag("/", method: "post", class: "form-horizontal") do %>
    <div class="form-group">
      <label for="categories" class="col-sm-2 control-label">Filter by category</label>
      <div class="col-sm-10">
        <select class="dropdown form-control" multiple="true" id="categories" name="categories[]">
          <%= options_for_select(@categories.map{|cat|[cat, cat.id] }, selected: params[:categories]) %>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Filter</button>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <table class="table table-bordered">
    <thead>
      <th>Product</th>
      <th>Description</th>
      <th>Price</th>
    </thead>
    <%= render(@products) || "<tr><td colspan=3><center>There are no products available.</center></td></tr>".html_safe %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductCatalog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if request.fullpath.starts_with? '/admin/' %>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Admin</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="<%= request.fullpath.starts_with?('/admin/categor') ? 'active' : '' %>">
                <%= link_to 'Categories', admin_categories_path, class: 'btn btn-link btn-xs' %>
              </li>
              <li class="<%= request.fullpath.starts_with?('/admin/product') ? 'active' : '' %>">
                <%= link_to 'Products', admin_products_path, class: 'btn btn-link btn-xs' %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<tr>
  <td>
    <%= product.name %>
  </td>
  <td>
    <%= product.description %>
  </td>
  <td>
    <%= product.price %>
  </td>
</tr>